---
title: "Miscanthus regional"
author: "David LeBauer"
date: "3/18/2015"
output: html_document
---


```{r, echo=FALSE,warning=FALSE}

library(PEcAn.all)

```
### Load PEcAn settings file.

Open and read in settings file for PEcAn run.


```{r, echo=FALSE, eval = FALSE, warning=FALSE}

settings.file <- c("/home/dlebauer/dev/biocro_regional/vignettes/illinois_mxg_settings.xml")

settings <- read.settings(settings.file)
settings$pfts <- get.trait.data(pfts = settings$pfts, 
                                modeltype = "BIOCRO", 
                                dbfiles = settings$run$dbfiles ,
                                database = settings$database$bety, 
                                forceupdate = "AUTO") 
run.meta.analysis(pfts = settings$pfts, random = TRUE, threshold = 1.2,
                  iterations = settings$meta.analysis$iter, 
                  dbfiles = settings$run$dbfiles, 
                  database = settings$database$bety)

run.write.configs(settings, settings$database$bety$write)

settings$run$host$qsub <- "qsub -l walltime=03:00:00,nodes=1:ppn=10 -N @NAME@ -o @STDOUT@ -e @STDERR@"
start.model.runs(settings, settings$database$bety$write) # Start ecosystem model runs

#settings$sensitivity.analysis$variable <- settings$ensemble$variable <- "TVeg"
get.results(settings = settings)

run.sensitivity.analysis()      # Run sensitivity analysis and variance decomposition on model output

run.ensemble.analysis(plot.timeseries=TRUE)  	      # Run ensemble analysis on model output. 
```

### Analysis for CyberGIS Demo

```{r}
library(data.table)
library(ggplot2)


files <- data.table(run = 9982:10481)
#files <- fread("../run/runs.txt")[, list(filename = file.path(V1, "biocro_output.RData"))]

allout <- list()
for(i in 1:length(files$run)){
  run <- files$run[i]
  filename = file.path("~/pecan_remote/205/out", run, "annual.result.RData")
  load(filename)
  allout[[i]] <- cbind(run = run, annual.result[, list(lat, lon, year, yield = Stem + Leaf)])
  rm(annual.result)
}


all <- rbindlist(allout)
save(all, file = "output/illinois_ensemble.RData")
write.csv(all, file = "output/illinois_ensemble.csv", row.names = FALSE)

range <- all[,list(mean = mean(yield)), by = 'lat,lon,year'][,list(range = max(mean) - min(mean)), by = 'lat,lon']

ranks <- all[, list(mean = mean(yield)), by = run][order(mean), ]
#ranks[5*(1:100) - 2]
sampled.runs <- ranks[5*(1:100)-2]

merge(sampled.runs[, list(run)], all, by = 'run', all.x = TRUE, all.y = FALSE)

```

### Climate

```{r climate-summary}
library(data.table)
library(ggplot2)

# copy on roger.ncsa.illinois.edu:/gpfs_scratch/biocro_output.RData 
load("~/biocro_output.RData")
theme_set(theme_bw())

z <- biocro_result[lat == 40.875 & lon == -87.875 ]
zz <- z[,list(lowyields = ifelse(year %in% c(2005,2007),TRUE,FALSE), doy, p = cumsum(precip), gdd = cumsum((tmax + tmin)/2)), by = 'year']

pdf("il_climate.pdf")

ggplot(data = zz, 
       aes(doy, gdd, group = year, color = lowyields)) + 
  geom_line() + 
  ggtitle("Cumulative GDD")

ggplot(data = zz, 
       aes(doy, p, group = year, color = lowyields)) + 
  geom_line() + 
  ggtitle("Cumulative Precipitation")



zz <- biocro_result[ , list(
  p = max(cumsum(precip)), 
  gdd = max(cumsum((tmax + tmin)/2))), 
  by = 'year,lat,lon']

zz[,`:=`( 
  # that frown `:=`( 
  #    is crazy syntax for 'add new variable'
  #    this is the data.table package. 
  #    Its great for this and many other reasons, 
  #    but dplyr is easier to learn and read
  lowyield = ifelse(year %in% c(2005,2007),TRUE,FALSE))]

ggplot(data = zzz, aes(x = year, y = p)) + 
  geom_line(aes(color = factor(lat))) + 
  ggtitle("total annual precip, by latitude")

ggplot(data = zzz, aes(x = year, y = gdd)) + 
  geom_line(aes(color = factor(lat))) + 
  ggtitle("gdd, by latitude")

dev.off()



```


## Calibration Runs

```{r il-mxg-calibration-sites}
library(dplyr)
library(data.table)
library(ggplot2)
d <- list(host = 'ebi-forecast.igb.illinois.edu',
          dbname = 'ebi_production',
          user = 'bety',
          password = 'bety')
bety <- src_postgres(host = d$host, user = d$user, password = d$password, dbname = d$dbname)

species <- tbl(bety, 'species') %>% 
  mutate(specie_id = id) %>% 
  select(specie_id, scientificname, genus) 

sites <- tbl(bety, sql(
  paste("select id as site_id, st_y(st_centroid(sites.geometry)) AS lat,",
        "st_x(st_centroid(sites.geometry)) AS lon,",
        " sitename, city, country from sites"))
  )

citations <- tbl(bety, 'citations') %>%
  select(citation_id = id, author, year, title)

yields <- tbl(bety, 'yields') %>%
  select(id, date, mean, statname, stat, site_id, specie_id, treatment_id, citation_id) %>% 
  left_join(species, by = 'specie_id') %>%
  left_join(sites, by = 'site_id') %>% 
  left_join(citations, by = 'citation_id')


managements_treatments <- tbl(bety, 'managements_treatments') %>%
  select(treatment_id, management_id)

treatments <- tbl(bety, 'treatments') %>% mutate(treatment_id = id) %>% 
  select(treatment_id, name, definition, control)

managements <- tbl(bety, 'managements') %>%
  filter(mgmttype %in% c('fertilizer_N', 'fertilizer_N_rate', 'planting', 'irrigation')) %>%
  mutate(management_id = id) %>%
  select(management_id, date, mgmttype, level, units) %>%
  left_join(managements_treatments, by = 'management_id') %>%
  left_join(treatments, by = 'treatment_id') 


nitrogen <- managements %>% 
  filter(mgmttype == "fertilizer_N_rate") %>%
  select(treatment_id, nrate = level)

planting <- managements %>% filter(mgmttype == "planting") %>%
  select(treatment_id, planting_date = date)

irrigation <- managements %>% 
  filter(mgmttype == 'irrigation') 

irrigation_rate <- irrigation %>% 
  filter(units == 'mm', !is.na(treatment_id)) %>% 
  group_by(treatment_id, year = sql("extract(year from date)"), units) %>% 
  summarise(irrig.mm = sum(level)) %>% 
  group_by(treatment_id) %>% 
  summarise(irrig.mm.y = mean(irrig.mm))

irrigation_boolean <- irrigation %>%
  collect %>%   
  group_by(treatment_id) %>% 
  mutate(irrig = as.logical(mean(level))) %>% 
  select(treatment_id, irrig = irrig)

irrigation_all <- irrigation_boolean %>% full_join(irrigation_rate, copy = TRUE)

grass_yields <- yields  %>% 
  filter(genus %in% c('Miscanthus', 'Panicum')) %>%
  left_join(nitrogen, by = 'treatment_id') %>%
  left_join(planting, by = 'treatment_id') %>%
  left_join(irrigation_all, by = 'treatment_id', copy = TRUE) %>% 
  collect

save(grass_yields, file = "~/dev/biocro_regional/data/grass_yields.RData")
```



```{r biocro-calibration-sites}
require(lubridate)
require(XML)
require(stringr)
require(dplyr)
require(data.table)
listToXml <- PEcAn.utils::listToXml

load("~/dev/biocro_regional/data/grass_yields.RData")
il_mxg <- grass_yields %>% 
  select(-year) %>% #publication year
  filter(author == "Arundale" & 
           genus == "Miscanthus" & 
           year(planting_date) %in% c(2004, 2002) & 
           lat<42.5 & lat > 37 & lon < -87.5 & lon > -91.5) %>% 
  select(site_id, sitename, lat, lon, planting_date, date, mean, se = stat, nrate, irrig, irrig.mm.y)

il_mxg_sites <- il_mxg %>% 
  select(site_id, sitename, lat, lon, planting_date, date) %>%  
  group_by(sitename, lat, lon, planting_date) %>% 
  mutate(start = ymd(planting_date), 
         end = max(ymd(date))) %>% 
  distinct %>% 
  setDT

sitenames <- il_mxg_sites %>%
  mutate(short_sitename = gsub("-", "", gsub("of ","",sitename))) %>%
  mutate(short_sitename = gsub(" ", "_", word(short_sitename, 1, 2))) %>% 
  select(sitename, short_sitename)

short_sitenames <- sitenames$short_sitename

sites <- split(il_mxg_sites %>% select(id = site_id, lat, lon), 
               f = 1:nrow(il_mxg_sites))
runs  <- split(il_mxg_sites %>% select(start, end), 
               f = 1:nrow(il_mxg_sites))

names(runs) <- names(sites) <- short_sitenames

settings <- list()
settings.dir <- "/home/dlebauer/dev/biocro_regional/inst/extdata/calibration_runs"
f <- function(x){

  mxg_settings <- file.path(settings.dir,"mxg_settings.xml")
  mxg_settings_list <- xmlToList(xmlParse(mxg_settings))
  
  rundir <- file.path("/home/dlebauer/pecan_remote/mxg_calibration", names(sites[x]))
  tmp <- mxg_settings_list
  tmp$outdir <- file.path(rundir)
  tmp$run$host$rundir <- file.path(rundir, "run")
  tmp$run$host$outdir <- file.path(rundir, "out")
  tmp$run$site <- sites[[x]]
  tmp$run$start.date <- runs[[x]]$start
  tmp$run$end.date <- runs[[x]]$end
  return(tmp)
}
settings <- lapply(short_sitenames, f)
names(settings) <- short_sitenames

settings.xml.list <- lapply(1:length(sites), 
                            function(x){
                              listToXml(settings[[x]], tag = 'pecan')
                            } )

names(settings.xml.list) <- short_sitenames

settings.files <- lapply(short_sitenames,
       function(x){
         saveXML(settings.xml.list[[x]], 
                 file = file.path(settings.dir, paste0(x, '.xml')))
                 })
names(settings.files) <- short_sitenames
save(settings.files, file = '~/dev/biocro_regional/inst/extdata/calibration_runs/settings.files.RData')
```

### BioCro Calibration

```{r pecan-calibration-workflow}
load('~/dev/biocro_regional/inst/extdata/calibration_runs/settings.files.RData')
library(PEcAn.all)
for(settings.file in settings.files){
  settings <- read.settings(settings.file)
#  settings$pfts <- get.trait.data(pfts = settings$pfts, 
#                                  modeltype = "BIOCRO", 
#                                  dbfiles = settings$run$dbfiles ,
#                                  database = settings$database$bety, 
#                                  forceupdate = "AUTO") 
#  run.meta.analysis(pfts = settings$pfts, random = settings$meta.analysis$random.effects, threshold = 1.2,
#                    iterations = settings$meta.analysis$iter, 
#                    dbfiles = settings$run$dbfiles, 
#                    database = settings$database$bety)
#  settings$model$binary <- gsub("regional", "point", settings$model$binary)
#  settings$run$host$qsub <- "qsub -l walltime=05:00:00,nodes=5:ppn=10 -N @NAME@ -o @STDOUT@ -e @STDERR@"
  
#  run.write.configs(settings, settings$database$bety$write)

  #system(paste("/home/dlebauer/dev/bety_manuscript/fix.sh", settings$rundir))
#  start.model.runs(settings, settings$database$bety$write) # Start ecosystem model runs

  get.results(settings)
  #run.sensitivity.analysis()
  #run.ensemble.analysis()
  
}


for(settings.file in settings.files){
#  settings <- read.settings(settings.file)
#  settings$model$binary <- gsub("regional", "point", settings$model$binary)
  get.results(settings, sa.ensemble.id = 212, ens.ensemble.id = 212)
}


```

```{r illinois-model-preds}
library(data.table)
library(dplyr)

all.ens.out <- list()
for(sitename in short_sitenames){
  outdir <- file.path("~/pecan_remote/mxg_calibration/", sitename)
  load(last(dir(outdir, pattern = "ensemble.samples", full.names = TRUE)))
  ens.out <- list()
  for(id in ens.run.ids$id){
    load(file.path(outdir, 'out', id, 'biocro_output.RData'))
    ens.out[[as.character(id)]] <- biocro_result[,list(site = sitename, run = id, Yield = max(Stem + Leaf), mean_temp = mean(tavg), mean_precip = mean(precip)), by = 'lat,lon,year']
  }
  
  all.ens.out[[sitename]] <- rbindlist(ens.out)
}

## should be moved to run_biocro function

correct.yield <- function(biocro_result){
  start <- min(biocro_result$year)
  if(diff(range(biocro_result$year)) > 15){
    stop('only have correction values for 15 yr')
  } 
  # correction
  # lessur = c(0.3, 0.5, 0.8, 1, 1.2, 1.1, 1, 0.95, 0.9, 0.85, 0.8, 0.77, 0.74, 0.7, 0.65)
  # arundale = c(NA, NA, 0.62, 0.90, 1, 0.97, 0.86, 0.72, 0.67, 0.67, 0.66)
  correction <- c(0.3, 0.5, 0.62, 0.90, 1, 0.97, 0.86, 0.72, 0.67, 0.67, 0.66)
  yield_correction <- data.table(year = start + 0:(length(correction) - 1), adjust = correction)
  
  a <- merge(biocro_result, yield_correction, by = 'year') 
  a[, `:=`(corrected_yield = Yield * adjust)]
  return(a)
}

all.ens <- rbindlist(lapply(all.ens.out, correct.yield))

load("~/dev/biocro_regional/data/grass_yields.RData")
obs_mxg <- grass_yields %>% 
  collect %>% 
  select(-year) %>% #publication year
  mutate(year = year(ymd(date))) %>% 
  filter(genus == "Miscanthus" & author == "Arundale" & !(year(planting_date) == 2009)) %>%
  setDT 

# look at start / end dates for IL  
sites <- obs_mxg[lat<42.5 & lat > 37 & lon < -87.5 & lon > -91.5, 
                 list(planting_date = unique(year(planting_date)), begin = min(year), end = max(year)), by = sitename] %>% 
  cbind(dirname = short_sitenames)

obs_mxg <- merge(obs_mxg, sites, by = 'sitename')

obs_mxg$sitename <- obs_mxg$dirname
obs_mxg[, `:=`(nrate = ifelse(is.na(nrate), 0, nrate))]
theme_set(theme_bw())
setnames(all.ens, "site", "sitename")
ggplot() + 
  geom_line(data = all.ens, aes(year, corrected_yield, group = run), alpha = 0.2) + 
  #geom_line(data = all.ens, aes(year, Yield, group = run), alpha = 0.2, color = 'red') + 
  geom_point(data = obs_mxg[sitename %in% unique(all.ens$sitename)], aes(year, mean, size = nrate), color = 'red') +
  facet_wrap(~sitename)


```

## Yield Plots

```{r}


library(ggplot2)
library(maps)
illinois <- borders("county", "illinois", colour = "white")

theme_set(theme_minimal())
ggplot(data=stats) + geom_tile(aes(lon,lat, fill = mean)) +   scale_fill_gradientn(colours = rainbow(7)) + illinois

ggplot(data=range) + geom_tile(aes(lon,lat, fill = range)) +   scale_fill_gradientn(colours = rainbow(7)) + illinois

mean_timeseries <- all[,list(median = median(yield)), by = 'lat,lon,year']
ggplot(data = mean_timeseries)+ geom_tile(aes(lon,lat, fill = median)) +   scale_fill_gradientn(colours = rainbow(4)) + illinois + facet_wrap(~year)
```


