---
title: "IL Miscanthus Calibration"
author: "David LeBauer"
date: "August 26, 2015"
output: pdf_document
---




## Calibration Runs

```{r il-mxg-calibration-sites}
library(dplyr)
library(data.table)
library(ggplot2)
d <- list(host = 'ebi-forecast.igb.illinois.edu',
          dbname = 'ebi_production',
          user = 'bety',
          password = 'bety')
bety <- src_postgres(host = d$host, user = d$user, password = d$password, dbname = d$dbname)

species <- tbl(bety, 'species') %>% 
  mutate(specie_id = id) %>% 
  select(specie_id, scientificname, genus) 

sites <- tbl(bety, sql(
  paste("select id as site_id, st_y(st_centroid(sites.geometry)) AS lat,",
        "st_x(st_centroid(sites.geometry)) AS lon,",
        " sitename, city, country from sites"))
  )

citations <- tbl(bety, 'citations') %>%
  select(citation_id = id, author, year, title)

yields <- tbl(bety, 'yields') %>%
  select(id, date, mean, statname, stat, site_id, specie_id, 
         treatment_id, citation_id) %>% 
  left_join(species, by = 'specie_id') %>%
  left_join(sites, by = 'site_id') %>% 
  left_join(citations, by = 'citation_id')


managements_treatments <- tbl(bety, 'managements_treatments') %>%
  select(treatment_id, management_id)

treatments <- tbl(bety, 'treatments') %>% mutate(treatment_id = id) %>% 
  select(treatment_id, name, definition, control)

managements <- tbl(bety, 'managements') %>%
  filter(mgmttype %in% c('fertilizer_N', 'fertilizer_N_rate', 'planting', 'irrigation')) %>%
  mutate(management_id = id) %>%
  select(management_id, date, mgmttype, level, units) %>%
  left_join(managements_treatments, by = 'management_id') %>%
  left_join(treatments, by = 'treatment_id') 


nitrogen <- managements %>% 
  filter(mgmttype == "fertilizer_N_rate") %>%
  select(treatment_id, nrate = level)

planting <- managements %>% filter(mgmttype == "planting") %>%
  select(treatment_id, planting_date = date)

irrigation <- managements %>% 
  filter(mgmttype == 'irrigation') 

irrigation_rate <- irrigation %>% 
  filter(units == 'mm', !is.na(treatment_id)) %>% 
  group_by(treatment_id, year = sql("extract(year from date)"), units) %>% 
  summarise(irrig.mm = sum(level)) %>% 
  group_by(treatment_id) %>% 
  summarise(irrig.mm.y = mean(irrig.mm))

irrigation_boolean <- irrigation %>%
  collect %>%   
  group_by(treatment_id) %>% 
  mutate(irrig = as.logical(mean(level))) %>% 
  select(treatment_id, irrig = irrig)

irrigation_all <- irrigation_boolean %>%
  full_join(irrigation_rate, copy = TRUE)

grass_yields <- yields  %>% 
  filter(genus %in% c('Miscanthus', 'Panicum')) %>%
  left_join(nitrogen, by = 'treatment_id') %>%
  left_join(planting, by = 'treatment_id') %>%
  left_join(irrigation_all, by = 'treatment_id', copy = TRUE) %>% 
  collect

save(grass_yields, file = "~/dev/biocro_regional/data/grass_yields.RData")
```



```{r biocro-calibration-sites}
require(lubridate)
require(XML)
require(stringr)
require(dplyr)
require(data.table)
listToXml <- PEcAn.utils::listToXml

load("~/dev/biocro_regional/data/grass_yields.RData")
il_mxg <- grass_yields %>% 
  select(-year) %>% #publication year
  filter(author == "Arundale" & 
           genus == "Miscanthus" & 
           year(planting_date) %in% c(2004, 2002) & 
           lat<42.5 & lat > 37 & lon < -87.5 & lon > -91.5) %>% 
  select(site_id, sitename, lat, lon, planting_date, date, mean, se = stat, nrate, irrig, irrig.mm.y)
save(il_mxg, file = "~/dev/biocro_regional/data/il_mxg.RData")
il_mxg_sites <- il_mxg %>% 
  select(site_id, sitename, lat, lon, planting_date, date) %>%  
  group_by(sitename, lat, lon, planting_date) %>% 
  mutate(start = ymd(planting_date), 
         end = max(ymd(date))) %>% 
  distinct %>% 
  setDT

sitenames <- il_mxg_sites %>%
  mutate(short_sitename = gsub("-", "", gsub("of ","",sitename))) %>%
  mutate(short_sitename = gsub(" ", "_", word(short_sitename, 1, 2))) %>% 
  select(sitename, short_sitename)

short_sitenames <- sitenames$short_sitename

save(short_sitenames, file = 'data/short_sitenames.RData')

sites <- split(il_mxg_sites %>% select(id = site_id, lat, lon), 
               f = 1:nrow(il_mxg_sites))
runs  <- split(il_mxg_sites %>% select(start, end), 
               f = 1:nrow(il_mxg_sites))

names(runs) <- names(sites) <- short_sitenames

settings <- list()
settings.dir <- "/home/dlebauer/dev/biocro_regional/inst/extdata/calibration_runs"
f <- function(x){

  mxg_settings <- file.path(settings.dir,"mxg_settings.xml")
  mxg_settings_list <- xmlToList(xmlParse(mxg_settings))
  
  rundir <- file.path("/home/dlebauer/pecan_remote/mxg_calibration", names(sites[x]))
  tmp <- mxg_settings_list
  tmp$outdir <- file.path(rundir)
  tmp$run$host$rundir <- file.path(rundir, "run")
  tmp$run$host$outdir <- file.path(rundir, "out")
  tmp$run$site <- sites[[x]]
  tmp$run$start.date <- runs[[x]]$start
  tmp$run$end.date <- runs[[x]]$end
  return(tmp)
}
settings <- lapply(short_sitenames, f)
names(settings) <- short_sitenames

settings.xml.list <- lapply(1:length(sites), 
                            function(x){
                              listToXml(settings[[x]], tag = 'pecan')
                            } )

names(settings.xml.list) <- short_sitenames

settings.files <- lapply(short_sitenames,
       function(x){
         saveXML(settings.xml.list[[x]], 
                 file = file.path(settings.dir, paste0(x, '.xml')))
                 })
names(settings.files) <- short_sitenames
save(settings.files, file = '~/dev/biocro_regional/inst/extdata/calibration_runs/settings.files.RData')
```

### BioCro Calibration

```{r pecan-calibration-workflow}
load('~/dev/biocro_regional/inst/extdata/calibration_runs/settings.files.RData')
library(PEcAn.all)

d <- settings$University_Illinois$database$bety
bety <- src_postgres(host = d$host, user = d$user, password = d$password, dbname = d$dbname)
ensembles <- tbl(bety, 'ensembles')

for(settings.file in settings.files){
  settings <- read.settings(settings.file)
}

for(dir in short_sitenames){
  settings.file <-file.path("/home/dlebauer/pecan_remote/mxg_calibration", dir, "pecan.xml")
  settings <- read.settings(settings.file)

#  settings$pfts <- get.trait.data(pfts = settings$pfts, 
#                                  modeltype = "BIOCRO", 
#                                  dbfiles = settings$run$dbfiles ,
#                                  database = settings$database$bety, 
#                                  forceupdate = "AUTO") 
#  run.meta.analysis(pfts = settings$pfts, random = settings$meta.analysis$random.effects, threshold = 1.2,
#                    iterations = settings$meta.analysis$iter, 
#                    dbfiles = settings$run$dbfiles, 
#                    database = settings$database$bety)
#  settings$model$binary <- gsub("regional", "point", settings$model$binary)
#  settings$run$host$qsub <- "qsub -l walltime=05:00:00,nodes=5:ppn=10 -N @NAME@ -o @STDOUT@ -e @STDERR@"
  
#  run.write.configs(settings, settings$database$bety$write)

  #system(paste("/home/dlebauer/dev/bety_manuscript/fix.sh", settings$rundir))
#  start.model.runs(settings, settings$database$bety$write) # Start ecosystem model runs

  sensitivity_id <- ensembles %>% 
    filter(workflow_id == settings$workflow$id) %>% 
    filter(runtype == 'sensitivity analysis') %>% 
    dplyr::select(id) %>% collect %>% as.numeric
  ensemble_id <- ensembles %>% 
    filter(workflow_id == settings$workflow$id) %>% 
    filter(runtype == 'ensemble') %>% 
    dplyr::select(id) %>% collect %>% as.numeric
  get.results(settings, sa.ensemble.id = sensitivity_id, ens.ensemble.id = ensemble_id)
  run.sensitivity.analysis(ensemble.id = sensitivity_id)
  run.ensemble.analysis(ensemble.id = ensemble_id)
  
}


```



```{r illinois-model-preds}
library(data.table)
library(dplyr)
load('data/short_sitenames.RData')
all.ens.out <- list()
for(sitename in short_sitenames){
  outdir <- file.path("~/pecan_remote/mxg_calibration/", sitename)
  load(last(dir(outdir, pattern = "ensemble.samples", full.names = TRUE)))
  ens.out <- list()
  for(id in ens.run.ids$id){
    load(file.path(outdir, 'out', id, 'biocro_output.RData'))
    ens.out[[as.character(id)]] <- biocro_result[,list(site = sitename, run = id, Yield = max(Stem + Leaf), mean_temp = mean(tavg), mean_precip = mean(precip)), by = 'lat,lon,year']
  }
  
  .all <-  rbindlist(ens.out)[,`:=`(run = frank(run, ties.method = 'dense'))]
  all.ens.out[[sitename]] <- .all
}


```


Correcting yield output using Ricker function from Lesur et al 2013 (see file `biocro_regional/lesur/lesur_mxg_correction.Rmd`)

| Parameter |	Old | New |
|--|--|--|
|$\phi_1$	|4.37| 4.12 |
|$\phi_2$	|1.21|1.12|
|$\phi_3$	|1.69| 0.13|

```{r lesur-correction}
## should be moved to run_biocro function



ricker <- function(t, phi1 = 1, phi2 = 1, phi3 = 1) {
  y <- phi1 * (t^phi2) * exp(-phi3 * t)
  return(y)
}

# Arundale parms from fig 2b
fig2b_mxg <- data.table(age = 3:10, 
                        mean = c(21.5, 31.3, 34.6, 33.8, 29.7, 25.09, 23.2))

nls(mean ~ a * (age^b) * exp(-c * age), 
    data = fig2b_mxg, 
    start=list(a = 4, b = 1.4, c = 0.24))

correct.yield <- function(biocro_result, age_correction = 1, harvest_correction = 1){
  years <- sort(unique(biocro_result$year))

  # correction
  if(!age_correction == 1){
    if(age_correction == 'lesur'){
      k <- ricker(1:length(years), 4.12, 1.12, 0.13)
      age_correction <- k/max(k)    
    } else if (age_correction == 'arundale'){
      k <- ricker(1:length(years), 5.7, 2.5, 0.46)
      age_correction <- k/max(k)
    }
  }

  # from Miguez et al 2013
  # http://onlinelibrary.wiley.com/doi/10.1111/j.1757-1707.2011.01150.x/epdf; 
  # multiplied by 0.67 to take account of losses in senescence, postsenescence, 
  # and during harvest (Clifton-Brown et al., 2004; Heaton et al., 2008).
  correction <- data.table(year = years, 
                           adjust = age_correction * harvest_correction)
  
  a <- merge(biocro_result, correction, by = 'year') 
  a[, `:=`(corrected_yield = Yield * adjust)]
  return(a)
}
.all <- lapply(all.ens.out, function(x) correct.yield(x, age_correction = 'lesur'))
all.ens <- rbindlist(.all)
all.ens[,`:=`(sitename = site)]
save(all.ens, file = "data/all.ens.RData")
```


```{r load-mxg-obs}
load("~/dev/biocro_regional/data/grass_yields.RData")
library(lubridate)
library(dplyr)
obs_mxg <- grass_yields %>% 
  collect %>% 
#  select(-year) %>% #publication year
  mutate(year = year(ymd(date))) %>% 
  filter(genus == "Miscanthus" & author == "Arundale" & !(year(planting_date) == 2009)) %>%
  setDT 

# look at start / end dates for IL  
sites <- obs_mxg[lat<42.5 & lat > 37 & lon < -87.5 & lon > -91.5, 
                 list(planting_date = unique(year(planting_date)), begin = min(year), end = max(year)), by = sitename] %>% 
  cbind(dirname = short_sitenames)

obs_mxg <- merge(obs_mxg, sites, by = 'sitename')

obs_mxg$sitename <- obs_mxg$dirname
obs_mxg[, `:=`(nrate = ifelse(is.na(nrate), 0, nrate))]
theme_set(theme_bw())
setnames(all.ens, "site", "sitename")

save(obs_mxg, file = "~/dev/biocro_regional/data/obs_mxg.RData")

```


```{r plot-model-obs}
load("data/all.ens.RData")
load("data/obs_mxg.RData")


o <- obs_mxg %>% 
  group_by(year, sitename) %>% 
  summarise(mean = mean(mean), se = sqrt(sum(stat^2))) 

all.ens$sitename <- as.factor(all.ens$sitename)
levels(all.ens$sitename) <- gsub("_", " ", levels(all.ens$sitename))

o$sitename <- as.factor(o$sitename)
levels(o$sitename) <- gsub("_", " ", levels(o$sitename))

ggplot() + xlim(c(2006.7, 2010.3)) + 
  #geom_line(data = all.ens, aes(year, corrected_yield, group = run), alpha = 0.01, size = 1) + 
  geom_line(data = all.ens, aes(year, 0.67 * Yield, group = run), alpha = 0.01) + 
  geom_pointrange(data = o, aes(year, mean, ymin = mean - se, ymax = mean + se), color = 'red') +
  geom_line(data = all.ens[run == 339], aes(year, 0.67 * Yield), color = 'blue') + 
  facet_wrap(~sitename, ncol = 4) +
  ylab("Yield (Mg/ha)") +
  xlab("Year")

ggplot(all.ens) + geom_point(aes(mean_temp, Yield, color= mean_precip), alpha = 0.2) + scale_color_gradientn(colours =  c('grey', 'blue'))

ggplot(all.ens) + geom_point(aes(mean_precip, Yield, color = mean_temp), alpha = 0.2) + scale_color_gradientn(colours =  c('yellow', 'red'))

ggplot() + xlim(2007,2010) +
  geom_line(data = all.ens, aes(year, corrected_yield), size = 2) + 
  #geom_line(data = all.ens, aes(year, Yield, group = run), alpha = 0.2, color = 'red') + 
  geom_point(data = obs_mxg[sitename %in% unique(all.ens$sitename) & nrate >= 100], aes(jitter(year), mean), color = 'red') +
  facet_wrap(~sitename, ncol = 2)

```

### Calibration

```{r}
install("~/dev/pecan.calibrator")
```

```{r message = FALSE}

require(data.table)
require(knitr)
require(ggplot2)
require(dplyr)

require(PEcAn.calibrator)

theme_set(theme_minimal())
```


```{r}
load("~/dev/biocro_regional/data/obs_mxg.RData")
load("~/dev/biocro_regional/data/all.ens.RData")

load("~/pecan_remote/mxg_calibration/University_Illinois/samples.Rdata")
load("~/pecan_remote/mxg_calibration/University_Illinois/pft/Miscanthus_x_giganteus/prior.distns.Rdata")

load("~/pecan_remote/mxg_calibration/University_Illinois/ensemble.output.262.Yield.2002.2010.Rdata")
quantiles <- rownames(sa.samples$Miscanthus_x_giganteus)


```


### Identify best run, compare to data 

```{r}

library(tidyr)
theta <- data.table(ensemble.samples$Miscanthus_x_giganteus, rep = 0, weight = 0)

### standardize long and short sitenames
sites <- cbind(
  obs_mxg[, list(sitename = unique(sitename)[order(unique(sitename))])],
  all.ens[ , list(site = unique(site)[order(unique(site))])])

### observed data
obs <- obs_mxg[, list(site = sitename, yield = mean(mean), n = length(mean), se = mean(stat)), by = 'sitename,year'][,list(site, year, xobs = yield, se)]
  

mod <- all.ens[ , list(xpred = Yield), by = 'site,run,year']
setkeyv(obs, c('site', 'year'))
setkeyv(mod, c('site', 'year'))

all <- merge(obs, mod, by = c('site','year'))

all_bysite <- all[,list(xobs = mean(xobs), xpred = mean(xpred)), by = 'site,run']


## estimate sd
obs_mxg %>% dplyr::select(stat) %>%
  summarise(mean(stat, na.rm = TRUE))

all[,`:=`(xpred = 0.66 * xpred)]
l <- all[,list(xobs = mean(xobs), xpred = mean(xpred), 
               d = mean(-dnorm(xobs, xpred, se)),
               #d = sum(-dlnorm(log(xobs), log(xpred), sqrt(log(se^2/xobs)^2 + 1))), 
               rmse = mean(sqrt((xpred - xobs)^2 / length(xobs)))), 
  by = 'run,site']#[,`:=`(site = as.factor(site))]

l <- l[,list(xpred = mean(xpred), xobs = mean(xobs), rmse=mean(rmse), d = mean(d)), by = 'run']
l[,plot(xpred, d)]
l[,plot(xpred, rmse)]

l[which.min(rmse)]
l[which.min(d)]

ggplot() + 
  geom_point(data = all, aes(site, xpred), color = 'grey') + 
  geom_point(data = all[run == 154], aes(site, xpred), color = 'darkgreen', size = 4) + 
    geom_point(data = all[run == 339], aes(site, xpred), color = 'red', size = 4) + 
  geom_point(data = all[run == 309], aes(site, xpred), color = 'orange', size = 4)+
    geom_point(data = all, aes(site, xobs), size = 4)




all_bysite <- all[,list(xobs = mean(xobs), xpred = mean(xpred)), by = 'site,run']

ggplot() + 
  geom_point(data = all_bysite, aes(site, xpred), color = 'grey') + 
  geom_point(data = all_bysite, aes(site, xobs), size = 4) +
  geom_point(data = all_bysite[run == 154], aes(site, xpred), color = 'darkgreen', size = 4) + 
    geom_point(data = all_bysite[run == 339],# min rmse
               aes(site, xpred), color = 'red', size = 4) 

### 339 has best fit RMSE


```

### Particle filter

```{r}

weights <- all %>%
  mutate(d = dnorm(xpred - xobs, 0, 5)) %>% 
  mutate(w = d/sum(d)) %>%
  group_by(run) %>%
  summarize(w = sum(w)) %>%
  mutate(cdf = cumsum(w),
         s = seq(rand, 1-rand, by = 1/len),
         p = ifelse(s <= cdf, s, NA))


theta2 <- particle.filter(codeOutput = mod, predictions = obs, mean = 0.5, stdev = 0.1, n = 1, theta = theta)

```

###

```{r plots}



```


### https://github.com/ebimodeling/biocro_regional/issues/16

```{r}
  
load("~/annual.result.RData")  
require(data.table)
require(sp)
require(raster)


# Correct yield
ricker <- function(t, phi1 = 1, phi2 = 1, phi3 = 1) {
  y <- phi1 * (t^phi2) * exp(-phi3 * t)
  return(y)
}

correct.yield <- function(biocro_result){
  start <- min(biocro_result$year)

  # lesur correction
  #corrected_lessur <- ricker(0:20, 4.12, 1.12, 0.13)
  corrected_arundale <- ricker(0:20, 5.2, 2.6, 0.46)
  age_correction <- corrected_arundale/max(corrected_arundale)

  # from Miguez et al 2013
  # http://onlinelibrary.wiley.com/doi/10.1111/j.1757-1707.2011.01150.x/epdf; 
  # multiplied by 0.67 to take account of losses in senescence, postsenescence, 
  # and during harvest (Clifton-Brown et al., 2004; Heaton et al., 2008).
  harvest_correction <- 0.67 
  correction <- age_correction * harvest_correction

  correction <- data.table(year = start + 0:(length(correction) - 1), adjust = correction)

  a <- merge(biocro_result, correction, by = 'year') 
  a[, `:=`(corrected_yield = (Stem + Leaf) * adjust)]
  return(a)
}
correct_yield <- correct.yield(annual.result)

# funtion to create a raster
createRaster <- function(df, brks, cols, name) {
  r <- raster(ncols=16, nrows=23, xmn=-91.50, xmx=-87.50, ymn=37.00, ymx=42.75)
  y <- df$lat
  x <- df$lon
  xy <- cbind(x,y)
  r0 <- rasterize(xy, r, df$corrected_yield, fun=mean)
  plot(r0, breaks=brks, col=cols, main=name)
  #plot(counties.il, add=T)
}

  
  
```